export const evt = {
  INITIALIZE_DB: 'initialize-db',
  ROUTE_CHANGED: 'route/changed',
  NAV_TO: 'nav/to',
  SET_TODO_TEXT: 'todo/set-text',
  CHANGE_FILTER: 'filters/change',
  ADD_TODO: 'todo/add',
  TOGGLE_DONE: 'todo/toggle-status',
  BEGIN_REMOVE_TODOS: 'todo/begin-remove',
  TODOS_REMOVED: 'todo/removed',
  MARK_ALL_DONE: 'todo/mark-all-done',
  CLEAR_ALL: 'todo/clear-all',
  CLEAR_ALL_DONE: 'todo/clear-all-done',
  TODO_STATUS_CHANGED: 'todo/status-changed',
  SHOW_NOTIFICATION: 'notification/show',
  HIDE_NOTIFICATION: 'notification/hide',
}
